# Generated by Django 3.1.3 on 2021-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210204_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zaktualizowano'),
        ),
    ]
